global:
  # Add labels from a parent chart to all manifests.
  labels: {}

  # The Google Project ID.
  # [Required for Cloud SQL Proxy]
  projectID: some-id

# Override name of the Job definition.
fullnameOverride: ""

##################################################
#                      Job                       #
##################################################

job:
  # Labels and Annotations on the Job definition.
  labels: {}
  annotations: {}

  # Enable DataDog logging.
  dataDogLogs:
    enable: false

  # Possible values are OnFailure or Never.
  # https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-template
  restartPolicy: Never

  # Clean up finished Jobs (either Complete or Failed) automatically is to use a TTL mechanism
  # provided by a TTL controller for finished resources.
  ttlSecondsAfterFinished: 120
  
  # Assign a service account for your application.
  # This service account represents your application and is used for authentication
  # with Workload Identity. The service account must be Workload Identity enabled.
  serviceAccountName: default

  imagePullSecrets: []
    # - secret-name-here

  container:
    image: example-image
    tag: latest

    # Enable custom command
    # command: ["my-command"]
    # args: ["with", "--params=yes"]

    environment: {}
      # SOME_ENV: some-value

    envFromConfigmap: []
      # - configmap-name

    fieldRefEnvironment: {}
      # SOME_ENV: some-field-reference

    # Below list of kubernetes secret names will be mounted into the container
    # under the path /secrets/<secret-name>/<secret-key>
    secrets: []
    # - very-secret

    # Below list of configmaps will be mounted into he container.
    configMaps: []
    # - name: some-configmap
    #   mountPath: /some/path

  # Enable the Google Cloud SQL Proxy sidecar
  # Find the latest version here, https://gcr.io/cloudsql-docker/gce-proxy
  cloudSQLProxy:
    enable: false
    instanceName: sqlinstance-name

    # [Deprecated]
    # If specified, Cloud SQL Proxy will use the provided credentials file for authn
    # insted of application default login aka Workload Identity.
    # secretKeyName: google-service-account-key

    # Immutable, if not specified, region will default to europe-west3
    # region: europe-west3
